#pragma config(Sensor, in1,    arm,            sensorPotentiometer)
#pragma config(Sensor, in2,    sw,             sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rshaft,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  lshaft,         sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RightLift2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftLift2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RightLift1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LeftLift1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

int aut = 2;
void pre_auton()
{
  displayLCDNumber(1, 0, SensorValue[sw], 5);
  if(SensorValue(sw) <= 1000){
  	aut = 1;
  }
  else if(SensorValue[sw] > 1000 && SensorValue[sw] <= 2000){
  	aut = 2;
  }
  else{
  	aut = 3;
  }
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	if(SensorValue(sw) <= 1300){
  	aut = 1;
  }
  else if  (SensorValue(sw) <= 2600){
	aut = 3;
  }
  else{
  	aut = 2;
  }
	switch(aut){
		case 1:

					break;
	 case 2:

					break;
	case 3:

					break;

				}
}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]

while(1==1){
    clearLCDLine(0);
    clearLCDLine(1);
		displayLCDNumber(0, 0, SensorValue(arm), 5);
		displayLCDNumber(1, 0, SensorValue(lshaft), 5);

		//holonomic drive code
		motor[FL] =  -C1LY + C1LX + C1RX;
		motor[FR] =   C1LY + C1LX + C1RX;
		motor[BR] =   C1LY + C1LX - C1RX;
		motor[BL] =  -C1LY + C1LX - C1RX;

		//Lift
		if(vexRT[Btn6U] && SensorValue(arm) < 3950){
			motor[RightLift1] = 127;
			motor[RightLift2] = 127;
			motor[LeftLift1] = 127;
			motor[LeftLift2] = 127;
		}
		//Lift reverse
		else if (vexRT[Btn6D]/*&& sensorValue(arm) > 0*/){
			motor[RightLift1] = -127;
			motor[RightLift2] = -127;
			motor[LeftLift1] = -127;
			motor[LeftLift2] = -127;
		}
		else if(vexRT[Btn7U]){
			motor[RightLift1] = 127;
			motor[RightLift2] = 127;
			motor[LeftLift1] = 127;
			motor[LeftLift2] = 127;
		}
		//Lift reverse
		else if (vexRT[Btn7D]){
			motor[RightLift1] = -127;
			motor[RightLift2] = -127;
			motor[LeftLift1] = -127;
			motor[LeftLift2] = -127;
		}
		//Do nothing
		else{
			motor[RightLift1] = 0;
			motor[RightLift2] = 0;
			motor[LeftLift1] = 0;
			motor[LeftLift2] = 0;
		}

		//Opens claw
		if (vexRT[Btn5U] == true){
			motor[claw] = -127;
    	motor[claw2] = 127;
		}
		//closes claw
		else if (vexRT[Btn5D] == true){
			motor[claw] = 127;
    	motor[claw2] = -127;
	}
		//Do nothing
		else{
			motor[claw] = 0;
			motor[claw2] = 0;
		}

}
}
