#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotor1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftLift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftLift1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightLift1,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                    - NCHS 7133 RoboHawks -                                      *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  A tank control drive program which drives the base motors and lift motors    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{

  while(1 == 1)
  {
  	//if (abs(vexRT[Ch1])>50)//threshold for sideways control
  	//{

			//	motor[leftMotor] = -vexRT[Ch1];
				//motor[rightMotor1] = -vexRT[Ch1];
				//motor[leftMotor1]=vexRT[Ch1];
				//motor[rightMotor] = vexRT[Ch1];

  	//}

  	//else{

   	 motor[leftMotor]  = vexRT[Ch3];   // Left Joystick Y value
     motor[rightMotor] = vexRT[Ch2];   // Right Joystick Y value
   	 motor[leftMotor1]  = vexRT[Ch3];   // Left Joystick Y value
   	 motor[rightMotor1] = vexRT[Ch2];   // Right Joystick Y value
		//}

	//moves 6 bar up and down or stays the same

  if (vexRT[Btn6U]
  {
  	motor[leftLift]  = 127;
    motor[rightLift] = 127;

    motor[leftLift1]  = 127;
    motor[rightLift1] = 127;

	}

	else if (vexRT[Btn6D]
  {
  	motor[leftLift]  = -127;
    motor[rightLift] = -127;

    motor[leftLift1]  = -127;
    motor[rightLift1] = -127;

	}
  /* if (vexRT[Btn8D])
  {
  	motor[leftLift]  = -127;
    motor[rightLift] = -127;

	}*/
	else //if (!vexRT[Btn8D])
  {
  	motor[leftLift]  = 0;
    motor[rightLift] = 0;

    motor[leftLift1]  = 0;
    motor[rightLift1] = 0;

	}
 }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
