#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    arm,            sensorPotentiometer)
#pragma config(Sensor, in2,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FL,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           FR,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           BR,            tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           BL,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port6,           RightLift1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightLift2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftLift1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftLift2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task open(){
  while(sensorValue(clawPot) < 1000){
    if(sensorValue(clawPot) > 750){
      motor[claw] = 25;
      motor[claw] = 25;
    }
    else if(sensorValue(clawPot) > 500){
      motor[claw] = 50;
      motor[claw] = 50;
    }
    else{
      motor[claw] = 127;
      motor[claw] = 127;
    }

  }
}

task close(){
  while(sensorValue(clawPot) > 0){
    if(sensorValue(clawPot) < 500){
      motor[claw] = 50;
      motor[claw] = 50;
    }
    else if(sensorValue(clawPot) < 250){
      motor[claw] = 25;
      motor[claw] = 25;
    }
    else{
      motor[claw] = 127;
      motor[claw] = 127;
    }
  }
}

/*
		motor[FL] = -C1LY - C1LX - C1RX;
		motor[FR] =  C1LY - C1LX - C1RX;
		motor[BR] =  C1LY + C1LX - C1RX;
		motor[BL] = -C1LY + C1LX - C1RX;
		
		392 counts on high speed encoder makes 1 rotation
*/

task main()
{
	//Run Backwards
	while(nMotorEncoder[FL] < 392){
		motor[FL] = 127;
		motor[FR] = -127;
		motor[BR] = -127;
		motor[BL] = 127;
	}
}
