#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    arm,            sensorPotentiometer)
#pragma config(Sensor, in2,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FL,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           FR,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           BR,            tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           BL,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port6,           RightLift1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightLift2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftLift1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftLift2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]

task open(){
  while(sensorValue(clawPot) < 750){
    if(sensorValue(clawPot) > 500){
      motor[claw] = 25;
      motor[claw] = 25;
    }
    else if(sensorValue(clawPot) > 250){
      motor[claw] = 50;
      motor[claw] = 50;
    }
    else{
      motor[claw] = 127;
      motor[claw] = 127;
    }

  }
}

task close(){
  while(sensorValue(clawPot) > 0){
    if(sensorValue(clawPot) < 500){
      motor[claw] = -50;
      motor[claw] = -50;
    }
    else if(sensorValue(clawPot) < 250){
      motor[claw] = -25;
      motor[claw] = -25;
    }
    else{
      motor[claw] = -127;
      motor[claw] = -127;
    }
  }
}

task main()
{
while(1==1){
    clearLCDLine(0); 
		displayLCDNumber(0, 0, SensorValue(arm), 5);
  	displayLCDNumber(1, 0, SensorValue(clawPot), 5);
		//holonomic drive code
		motor[FL] = -C1LY - C1LX - C1RX;
		motor[FR] =  C1LY - C1LX - C1RX;
		motor[BR] =  C1LY + C1LX - C1RX;
		motor[BL] = -C1LY + C1LX - C1RX;

		//Lift
		if(VexRT[Btn6U] && sensorValue(arm) < 2500){
			motor[RightLift1] = 127;
			motor[RightLift2] = 127;
			motor[LeftLift1] = 127;
			motor[LeftLift2] = 127;
		}
		//Lift reverse
		else if (VexRT[Btn5U]&& sensorValue(arm) > 0){
			motor[RightLift1] = -127;
			motor[RightLift2] = -127;
			motor[LeftLift1] = -127;
			motor[LeftLift2] = -127;
		}
		//Do nothing
		else{
			motor[RightLift1] = 0;
			motor[RightLift2] = 0;
			motor[LeftLift1] = 0;
			motor[LeftLift2] = 0;
		}

		//Opens claw
		if(VexRT[Btn5D]){
			startTask(open());
		}
		//Reverses claw
		else if(VexRT[Btn6D]){
			startTask(close());
		}
		//Do nothing
		else{
			motor[claw] = 0;
			motor[claw2] = 0;
		}

}
}
