#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ArmFront,       sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           FR,            tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           BR,            tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]

task main()
{
while(1==1){
		//holonomic drive code
		motor[FL] = -C1LY - C1LX - C1RX;
		motor[FR] =  C1LY - C1LX - C1RX;
		motor[BR] =  C1LY + C1LX - C1RX;
		motor[BL] = -C1LY + C1LX - C1RX;

		//Lift
		if(VexRT[Btn5U] && SensorValue(ArmBack) == 0){
			motor[lift1] = 127;
			motor[lift2] = 127;
		}
		//Lift reverse
		else if (VexRT[Btn6U] && SensorValue(ArmFront) == 0){
			motor[lift1] = -127;
			motor[lift2] = -127;
		}
		//Do nothing
		else{
			motor[lift1] = 0;
			motor[lift2] = 0;
		}


		//Opens claw
		if(VexRT[Btn5D] && SensorValue(in1) < 180){
			motor[claw] = 127;
		}
		//Reverses claw
		else if(VexRT[Btn6D] && SensorValue(in1) > 0){
			motor[claw] = -127;
		}
		//Do nothing
		else{
			motor[claw] = 0;
		}
}
}
